applicationName: Simple Money Transfer API

server:
  applicationConnectors:
    - type: http
      port: 9090

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'src/schema.sql'
  
#logging:
#  level: INFO
  # Logger-specific levels.
#  loggers:
    # Redirects SQL logs to a separate file
    # org.hibernate.SQL:
    #  level: DEBUG